/**
 * 国家/地区名称标准化工具
 * 数据库中存储2位国家代码，前端显示时转换为全称
 */

// ISO 3166-1 alpha-2 到标准全称的映射
export const COUNTRY_CODE_MAP: Record<string, string> = {
  "CN": "China",
  "US": "United States",
  "CA": "Canada",
  "GB": "United Kingdom",
  "AU": "Australia",
  "JP": "Japan",
  "KR": "South Korea",
  "DE": "Germany",
  "FR": "France",
  "IT": "Italy",
  "ES": "Spain",
  "NL": "Netherlands",
  "BE": "Belgium",
  "CH": "Switzerland",
  "AT": "Austria",
  "SE": "Sweden",
  "NO": "Norway",
  "DK": "Denmark",
  "FI": "Finland",
  "IE": "Ireland",
  "PT": "Portugal",
  "GR": "Greece",
  "PL": "Poland",
  "CZ": "Czech Republic",
  "HU": "Hungary",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "HR": "Croatia",
  "RO": "Romania",
  "BG": "Bulgaria",
  "LT": "Lithuania",
  "LV": "Latvia",
  "EE": "Estonia",
  "LU": "Luxembourg",
  "MT": "Malta",
  "CY": "Cyprus",
  "IS": "Iceland",
  "LI": "Liechtenstein",
  "MC": "Monaco",
  "SM": "San Marino",
  "AD": "Andorra",
  "VA": "Vatican City",
  "TR": "Turkey",
  "RU": "Russia",
  "UA": "Ukraine",
  "BY": "Belarus",
  "MD": "Moldova",
  "GE": "Georgia",
  "AM": "Armenia",
  "AZ": "Azerbaijan",
  "KZ": "Kazakhstan",
  "UZ": "Uzbekistan",
  "KG": "Kyrgyzstan",
  "TJ": "Tajikistan",
  "TM": "Turkmenistan",
  "IN": "India",
  "PK": "Pakistan",
  "BD": "Bangladesh",
  "LK": "Sri Lanka",
  "NP": "Nepal",
  "BT": "Bhutan",
  "MV": "Maldives",
  "AF": "Afghanistan",
  "IR": "Iran",
  "IQ": "Iraq",
  "SY": "Syria",
  "LB": "Lebanon",
  "JO": "Jordan",
  "IL": "Israel",
  "PS": "Palestine",
  "SA": "Saudi Arabia",
  "YE": "Yemen",
  "OM": "Oman",
  "AE": "United Arab Emirates",
  "QA": "Qatar",
  "BH": "Bahrain",
  "KW": "Kuwait",
  "EG": "Egypt",
  "LY": "Libya",
  "TN": "Tunisia",
  "DZ": "Algeria",
  "MA": "Morocco",
  "MR": "Mauritania",
  "ML": "Mali",
  "NE": "Niger",
  "TD": "Chad",
  "SD": "Sudan",
  "ER": "Eritrea",
  "DJ": "Djibouti",
  "ET": "Ethiopia",
  "SO": "Somalia",
  "KE": "Kenya",
  "UG": "Uganda",
  "TZ": "Tanzania",
  "RW": "Rwanda",
  "BI": "Burundi",
  "CD": "DR Congo",
  "CG": "Congo",
  "GA": "Gabon",
  "GQ": "Equatorial Guinea",
  "ST": "Sao Tome and Principe",
  "CM": "Cameroon",
  "CF": "Central African Republic",
  "NG": "Nigeria",
  "BJ": "Benin",
  "TG": "Togo",
  "GH": "Ghana",
  "CI": "Ivory Coast",
  "LR": "Liberia",
  "SL": "Sierra Leone",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GM": "Gambia",
  "SN": "Senegal",
  "CV": "Cape Verde",
  "ZA": "South Africa",
  "NA": "Namibia",
  "BW": "Botswana",
  "ZW": "Zimbabwe",
  "MZ": "Mozambique",
  "ZM": "Zambia",
  "MW": "Malawi",
  "AO": "Angola",
  "MG": "Madagascar",
  "MU": "Mauritius",
  "SC": "Seychelles",
  "KM": "Comoros",
  "TH": "Thailand",
  "VN": "Vietnam",
  "MY": "Malaysia",
  "PH": "Philippines",
  "ID": "Indonesia",
  "SG": "Singapore",
  "BN": "Brunei",
  "KH": "Cambodia",
  "LA": "Laos",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "KP": "North Korea",
  "TW": "Taiwan",
  "HK": "Hong Kong",
  "MO": "Macau",
  "MX": "Mexico",
  "GT": "Guatemala",
  "BZ": "Belize",
  "SV": "El Salvador",
  "HN": "Honduras",
  "NI": "Nicaragua",
  "CR": "Costa Rica",
  "PA": "Panama",
  "CU": "Cuba",
  "JM": "Jamaica",
  "HT": "Haiti",
  "DO": "Dominican Republic",
  "PR": "Puerto Rico",
  "CO": "Colombia",
  "VE": "Venezuela",
  "GY": "Guyana",
  "SR": "Suriname",
  "GF": "French Guiana",
  "EC": "Ecuador",
  "PE": "Peru",
  "BO": "Bolivia",
  "BR": "Brazil",
  "PY": "Paraguay",
  "UY": "Uruguay",
  "AR": "Argentina",
  "CL": "Chile",
  "NZ": "New Zealand",
  "PG": "Papua New Guinea",
  "FJ": "Fiji",
  "SB": "Solomon Islands",
  "VU": "Vanuatu",
  "NC": "New Caledonia",
  "PF": "French Polynesia",
  "WS": "Samoa",
  "TO": "Tonga",
  "KI": "Kiribati",
  "TV": "Tuvalu",
  "NR": "Nauru",
  "PW": "Palau",
  "MH": "Marshall Islands",
  "FM": "Micronesia",
  "UK": "GB"
};

// 国家代码到中文名称的映射
export const COUNTRY_CODE_TO_ZH: Record<string, string> = {
  "CN": "中国",
  "US": "美国",
  "CA": "加拿大",
  "GB": "英国",
  "AU": "澳大利亚",
  "JP": "日本",
  "KR": "韩国",
  "DE": "德国",
  "FR": "法国",
  "IT": "意大利",
  "ES": "西班牙",
  "NL": "荷兰",
  "BE": "比利时",
  "CH": "瑞士",
  "AT": "奥地利",
  "SE": "瑞典",
  "NO": "挪威",
  "DK": "丹麦",
  "FI": "芬兰",
  "IE": "爱尔兰",
  "PT": "葡萄牙",
  "GR": "希腊",
  "PL": "波兰",
  "CZ": "捷克",
  "HU": "匈牙利",
  "SK": "斯洛伐克",
  "SI": "斯洛文尼亚",
  "HR": "克罗地亚",
  "RO": "罗马尼亚",
  "BG": "保加利亚",
  "LT": "立陶宛",
  "LV": "拉脱维亚",
  "EE": "爱沙尼亚",
  "LU": "卢森堡",
  "MT": "马耳他",
  "CY": "塞浦路斯",
  "IS": "冰岛",
  "LI": "列支敦士登",
  "MC": "摩纳哥",
  "SM": "圣马力诺",
  "AD": "安道尔",
  "VA": "梵蒂冈",
  "TR": "土耳其",
  "RU": "俄罗斯",
  "UA": "乌克兰",
  "BY": "白俄罗斯",
  "MD": "摩尔多瓦",
  "GE": "格鲁吉亚",
  "AM": "亚美尼亚",
  "AZ": "阿塞拜疆",
  "KZ": "哈萨克斯坦",
  "UZ": "乌兹别克斯坦",
  "KG": "吉尔吉斯斯坦",
  "TJ": "塔吉克斯坦",
  "TM": "土库曼斯坦",
  "IN": "印度",
  "PK": "巴基斯坦",
  "BD": "孟加拉国",
  "LK": "斯里兰卡",
  "NP": "尼泊尔",
  "BT": "不丹",
  "MV": "马尔代夫",
  "AF": "阿富汗",
  "IR": "伊朗",
  "IQ": "伊拉克",
  "SY": "叙利亚",
  "LB": "黎巴嫩",
  "JO": "约旦",
  "IL": "以色列",
  "PS": "巴勒斯坦",
  "SA": "沙特阿拉伯",
  "YE": "也门",
  "OM": "阿曼",
  "AE": "阿联酋",
  "QA": "卡塔尔",
  "BH": "巴林",
  "KW": "科威特",
  "EG": "埃及",
  "LY": "利比亚",
  "TN": "突尼斯",
  "DZ": "阿尔及利亚",
  "MA": "摩洛哥",
  "MR": "毛里塔尼亚",
  "ML": "马里",
  "NE": "尼日尔",
  "TD": "乍得",
  "SD": "苏丹",
  "ER": "厄立特里亚",
  "DJ": "吉布提",
  "ET": "埃塞俄比亚",
  "SO": "索马里",
  "KE": "肯尼亚",
  "UG": "乌干达",
  "TZ": "坦桑尼亚",
  "RW": "卢旺达",
  "BI": "布隆迪",
  "CD": "刚果民主共和国",
  "CG": "刚果",
  "GA": "加蓬",
  "GQ": "赤道几内亚",
  "ST": "圣多美和普林西比",
  "CM": "喀麦隆",
  "CF": "中非共和国",
  "NG": "尼日利亚",
  "BJ": "贝宁",
  "TG": "多哥",
  "GH": "加纳",
  "CI": "科特迪瓦",
  "LR": "利比里亚",
  "SL": "塞拉利昂",
  "GN": "几内亚",
  "GW": "几内亚比绍",
  "GM": "冈比亚",
  "SN": "塞内加尔",
  "CV": "佛得角",
  "ZA": "南非",
  "NA": "纳米比亚",
  "BW": "博茨瓦纳",
  "ZW": "津巴布韦",
  "MZ": "莫桑比克",
  "ZM": "赞比亚",
  "MW": "马拉维",
  "AO": "安哥拉",
  "MG": "马达加斯加",
  "MU": "毛里求斯",
  "SC": "塞舌尔",
  "KM": "科摩罗",
  "TH": "泰国",
  "VN": "越南",
  "MY": "马来西亚",
  "PH": "菲律宾",
  "ID": "印度尼西亚",
  "SG": "新加坡",
  "BN": "文莱",
  "KH": "柬埔寨",
  "LA": "老挝",
  "MM": "缅甸",
  "MN": "蒙古",
  "KP": "朝鲜",
  "TW": "中国台湾",
  "HK": "中国香港",
  "MO": "中国澳门",
  "MX": "墨西哥",
  "GT": "危地马拉",
  "BZ": "伯利兹",
  "SV": "萨尔瓦多",
  "HN": "洪都拉斯",
  "NI": "尼加拉瓜",
  "CR": "哥斯达黎加",
  "PA": "巴拿马",
  "CU": "古巴",
  "JM": "牙买加",
  "HT": "海地",
  "DO": "多米尼加",
  "PR": "波多黎各",
  "CO": "哥伦比亚",
  "VE": "委内瑞拉",
  "GY": "圭亚那",
  "SR": "苏里南",
  "GF": "法属圭亚那",
  "EC": "厄瓜多尔",
  "PE": "秘鲁",
  "BO": "玻利维亚",
  "BR": "巴西",
  "PY": "巴拉圭",
  "UY": "乌拉圭",
  "AR": "阿根廷",
  "CL": "智利",
  "NZ": "新西兰",
  "PG": "巴布亚新几内亚",
  "FJ": "斐济",
  "SB": "所罗门群岛",
  "VU": "瓦努阿图",
  "NC": "新喀里多尼亚",
  "PF": "法属波利尼西亚",
  "WS": "萨摩亚",
  "TO": "汤加",
  "KI": "基里巴斯",
  "TV": "图瓦卢",
  "NR": "瑙鲁",
  "PW": "帕劳",
  "MH": "马绍尔群岛",
  "FM": "密克罗尼西亚"
};

/**
 * 将国家代码转换为标准全称
 */
export function getCountryFullName(code: string | null | undefined): string {
  if (!code) return 'Unknown';
  const upperCode = code.toUpperCase();
  return COUNTRY_CODE_MAP[upperCode] || code;
}

/**
 * 将国家代码转换为中文名称
 */
export function getCountryChineseName(code: string | null | undefined): string {
  if (!code) return '未知';
  const upperCode = code.toUpperCase();
  return COUNTRY_CODE_TO_ZH[upperCode] || getCountryFullName(code);
}

/**
 * 标准化国家代码（统一为2位大写）
 */
export function standardizeCountryCode(country: string | null | undefined): string | null {
  if (!country || country === 'Unknown' || country === 'unknown') {
    return null;
  }
  
  const trimmed = country.toString().trim();
  
  // 如果已经是2位代码
  if (/^[A-Za-z]{2}$/.test(trimmed)) {
    return trimmed.toUpperCase();
  }
  
  // 查找全名对应的代码
  const upperTrimmed = trimmed.toUpperCase();
  for (const [name, code] of Object.entries(COUNTRY_CODE_MAP)) {
    if (name.toUpperCase() === upperTrimmed) {
      return code;
    }
  }
  
  return trimmed;
}
