'use client';

import React, { useState } from 'react';
import { Button, Card, Input } from '@/components/ui';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/Select';
import { FileText, Download, Loader2, Search, CheckCircle } from 'lucide-react';
import { useLocale } from '@/lib/i18n/LocaleProvider';

const reportTypes = [
  { value: 'market_analysis', label: 'Market Access Analysis' },
  { value: 'competitor_analysis', label: 'Competitor Analysis' },
  { value: 'risk_assessment', label: 'Risk Assessment' },
  { value: 'regulatory_summary', label: 'Regulatory Summary' },
];

const languages = [
  { value: 'en', label: 'English' },
  { value: 'zh', label: '中文' },
];

export default function ReportsPage() {
  const locale = useLocale();
  const [companyName, setCompanyName] = useState('');
  const [reportType, setReportType] = useState('market_analysis');
  const [language, setLanguage] = useState('en');
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<string | null>(null);
  const [generated, setGenerated] = useState(false);

  const handleGenerate = async () => {
    if (!companyName.trim()) return;

    setLoading(true);
    setGenerated(false);

    try {
      const response = await fetch('/api/report/medplum', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          companyName,
          reportType,
          language,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate report');
      }

      const data = await response.json();
      setReport(data.data.report);
      setGenerated(true);
    } catch (error) {
      console.error('Report generation error:', error);
      // Fallback to mock data if Medplum API fails
      const reportContent = generateMockReport(companyName, reportType, language);
      setReport(reportContent);
      setGenerated(true);
    } finally {
      setLoading(false);
    }
  };

  const generateMockReport = (company: string, type: string, lang: string) => {
    const typeNames: Record<string, string> = {
      market_analysis: lang === 'zh' ? 'Market Access Analysis' : 'Market Access Analysis',
      competitor_analysis: lang === 'zh' ? 'Competitor Analysis' : 'Competitor Analysis',
      risk_assessment: lang === 'zh' ? 'Risk Assessment' : 'Risk Assessment',
      regulatory_summary: lang === 'zh' ? 'Regulatory Summary' : 'Regulatory Summary',
    };

    return `# ${company} - ${typeNames[type]} Report

## Executive Summary

This report provides comprehensive analysis of ${company}'s compliance status in major global medical device markets.

## 1. Company Overview

- **Company Name**: ${company}
- **Analysis Date**: ${new Date().toLocaleDateString('en-US')}
- **Report Type**: ${typeNames[type]}
- **Data Source**: MDLooker Database

## 2. Market Analysis

### 2.1 FDA Registration
- 510(k) Submissions: 15
- PMA Submissions: 3
- Latest Registration: 2026-01-15

### 2.2 Other Markets
- NMPA: 8 registrations
- EUDAMED: 12 device registrations

## 3. Conclusions and Recommendations

Based on the analysis above, we recommend:
1. Focus on recent FDA regulatory changes
2. Strengthen EUDAMED data maintenance
3. Consider expanding into Asia-Pacific markets

---
*This report is generated by MDLooker AI for reference only*`;
  };

  const handleDownload = () => {
    if (!report) return;

    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `report-${companyName}-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-[calc(100vh-64px)] py-8 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 md:px-6 lg:px-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">{locale === 'zh' ? 'AI报告生成器' : 'AI Report Generator'}</h1>
          <p className="text-gray-500">{locale === 'zh' ? '使用AI生成专业医疗器械合规分析报告' : 'Generate professional medical device compliance analysis reports with AI'}</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-1">
            <Card className="p-6 sticky top-24">
              <h2 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
                <FileText className="w-5 h-5 text-[#339999]" />
                {locale === 'zh' ? '设置' : 'Settings'}
              </h2>

              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    {locale === 'zh' ? '目标企业' : 'Target Company'}
                  </label>
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                    <Input
                      value={companyName}
                      onChange={(e) => setCompanyName(e.target.value)}
                      placeholder={locale === 'zh' ? '输入企业名称' : 'Enter company name'}
                      className="pl-10"
                    />
                  </div>
                </div>

                <Select
                  value={reportType}
                  onValueChange={setReportType}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select report type" />
                  </SelectTrigger>
                  <SelectContent>
                    {reportTypes.map((type) => (
                      <SelectItem key={type.value} value={type.value}>
                        {type.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>

                <Select
                  value={language}
                  onValueChange={setLanguage}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select language" />
                  </SelectTrigger>
                  <SelectContent>
                    {languages.map((lang) => (
                      <SelectItem key={lang.value} value={lang.value}>
                        {lang.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>

                <Button
                  className="w-full bg-[#339999] hover:bg-[#2a8080]"
                  size="lg"
                  onClick={handleGenerate}
                  disabled={loading || !companyName.trim()}
                >
                  {loading ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      {locale === 'zh' ? '生成中...' : 'Generating...'}
                    </>
                  ) : (
                    <>
                      <FileText className="w-4 h-4 mr-2" />
                      {locale === 'zh' ? '生成报告' : 'Generate Report'}
                    </>
                  )}
                </Button>
              </div>

              <div className="mt-6 p-4 bg-[#339999]/5 rounded-lg">
                <h3 className="text-sm font-medium text-[#339999] mb-2">{locale === 'zh' ? '报告包含：' : 'Report includes:'}</h3>
                <ul className="text-sm text-gray-600 space-y-1">
                  <li>• {locale === 'zh' ? '全球市场分析' : 'Global market analysis'}</li>
                  <li>• {locale === 'zh' ? '注册统计' : 'Registration statistics'}</li>
                  <li>• {locale === 'zh' ? '合规风险评估' : 'Compliance risk assessment'}</li>
                  <li>• {locale === 'zh' ? '专业建议' : 'Professional recommendations'}</li>
                </ul>
              </div>
            </Card>
          </div>

          <div className="lg:col-span-2">
            <Card className="p-6 min-h-[600px]">
              {generated ? (
                <>
                  <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-2">
                      <CheckCircle className="w-5 h-5 text-green-500" />
                      <span className="font-medium text-gray-900">{locale === 'zh' ? '报告已生成' : 'Report Generated'}</span>
                    </div>
                    <Button variant="outline" onClick={handleDownload}>
                      <Download className="w-4 h-4 mr-2" />
                      {locale === 'zh' ? '下载' : 'Download'}
                    </Button>
                  </div>
                  <div className="prose prose-gray max-w-none">
                    <pre className="whitespace-pre-wrap font-mono text-sm text-gray-700 bg-gray-50 p-4 rounded-lg overflow-auto max-h-[500px]">
                      {report}
                    </pre>
                  </div>
                </>
              ) : (
                <div className="flex flex-col items-center justify-center h-full text-gray-400">
                  <FileText className="w-16 h-16 mb-4" />
                  <p className="text-lg">{locale === 'zh' ? '报告预览' : 'Report Preview'}</p>
                  <p className="text-sm">{locale === 'zh' ? '填写表单以生成报告' : 'Fill the form to generate a report'}</p>
                </div>
              )}
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
